name: Compile and release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: echo SCRIPTS_PATH=$(pwd) >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.11.x"
          version-file: ./scripting/att_firering.sp
        
      - name: Download SourcePawn plugin dependencies
        uses: Zabaniya001/SPDependy@v2
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Compile plugins
        run: |
          mkdir plugins
          spcomp -w234 -O2 -v2 -i"scripting/include" -i".temp/include" -o"plugins/att_firering.smx" scripting/att_firering.sp
        working-directory: ${{ env.SCRIPTS_PATH }}